CREATE TABLE HOBBY (
  ID      			 INTEGER AUTO_INCREMENT,
  NOM				 VARCHAR(255)
 );


CREATE TABLE LICORNE (
  ID      			 INTEGER AUTO_INCREMENT,
  NOM				 VARCHAR(255),
  ANNEE_NAISSANCE    INTEGER,
  POIDS				 INTEGER,
  PHOTO				 VARCHAR(255),
  ID_HOBBY			 INTEGER,
  FOREIGN KEY (ID_HOBBY) REFERENCES HOBBY (ID)
 );