
INSERT INTO HOBBY(NOM) VALUES ('BOXE');
INSERT INTO HOBBY(NOM) VALUES ('FOOTBALL');


INSERT INTO LICORNE(NOM,ANNEE_NAISSANCE, POIDS, PHOTO, ID_HOBBY) VALUES ('Rocky', 1995, 74, 'http://photos.com/rocky-unicorn.jpg', 1);
INSERT INTO LICORNE(NOM,ANNEE_NAISSANCE, POIDS, PHOTO, ID_HOBBY) VALUES ('Amy', 1990, 42, 'http://photos.com/amy-unicorn.jpg', 2);
